### PR TITLE
Update to PDL v2.037

### PR DESCRIPTION
**Pull request by zmughal**
Here is the start of my fixes to support native complex types in Test::PDL.

I believe that the `abs( got - expected ) < tol` approach should still work for
the native complex types.

What I am seeing is a problem with how bad values + stringification  interact
for native complex types and this causes some Test::PDL test failures in
`t/deep.t`:

On my machine:

```
0:main
$ use PDL; cdouble('[0 BAD]')->string
Argument "-8.9884656743115785e+307+0i" isn't numeric in subroutine entry at .../lib/site_perl/5.26.1/x86_64-linux/PDL/Core.pm line 1134.
[0+0i -8.9884656743115835e+307+0i]
```

Oddly, I'm not seeing this issue with `perlbot` in the `#pdl` IRC channel.

```
> eval: use PDL; $SIG{__WARN__} = sub{};  say cdouble('[0 BAD]'); # this gives different output on my computer with the same PDL version
[ perlbot] [0+0i BAD]
```

CC: @mohawk2

### CODE REVIEW

**Comment by mohawk2** [comment]
Let's not forget that the `< tol` idiom is a comparison, which isn't valid for complex numbers. You'd need to separately compare the real and imaginary bits.

**Comment by zmughal** [comment]
abs( Complex ) should be Real, right?

**Comment by mohawk2** [comment]
Ah, I missed the `abs`! Yes, that would work great.

**Comment by zmughal** [comment]
Possibly related https://github.com/PDLPorters/pdl/issues/302

**Comment by ebaudrez** [comment]
@mohawk2 , I've added you as a collaborator, and also as a co-maintainer on PAUSE. Would you be so kind to look at this, please? Thank you!! @zmughal and @mohawk2 thanks -again- for your work, much appreciated!

**Comment by zmughal** [comment]
Looks good to me, @mohawk2!

**Comment by mohawk2** [comment]
Now released as 0.15 (with limitations to native complex as noted in the docs)

**Pull request merged**
