### PR TITLE
Remove data-type restriction as PDL 2.039 supports right

### PR DESCRIPTION
**Pull request by mohawk2**
If there are no objections I will merge and release this. @ebaudrez @zmughal

### CODE REVIEW

**Comment by zmughal** [comment]
I'll run this locally first, but it looks fine.

There is not a CI on this repo yet is there?

**Comment by mohawk2** [comment]
There isn't yet. PRs welcome! ;-)

**Comment by zmughal** [comment]
Looks fine when running locally.

**Comment by mohawk2** [comment]
Released as 0.16

**Pull request merged**
