### PR TITLE
simplify t/import_options.t to reduce fragility

### PR DESCRIPTION
**Pull request by mohawk2**
This eliminates having to manipulate the symbol table. It also makes more explicit the global effect of imports by different packages. In other words, if I made a testing library that imported with a different `equal_types` setting, it would change the behaviour of other users. That is a fact, and not a good one, but this PR only makes testing simpler rather than addressing it.

### CODE REVIEW

**Review by ebaudrez — APPROVED** [review]
Go ahead. I've never been happy with the way the options had to be specified Test::PDL and I intend to overhaul it (some day). In the meantime, you can merge this.

**Comment by zmughal** [comment]
Looks good to me!

**Comment by mohawk2** [comment]
Thanks! I think the way to do this more robustly would be to having options stored per importing package, then each function-call would look at its caller-package to see which options to use. A slightly more clever-clever way would be when exporting functions, to wrap them in a closure that would do the same.

A problem for another day!

**Comment by ebaudrez** [comment]
> A problem for another day!
I couldn't agree more :D

**Pull request merged**
